# fly.toml app configuration file generated for electrohub-backend on 2025-08-12T21:00:13+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'electrohub-backend'
primary_region = 'jnb'

[build]

[env]
  PORT = '5000'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

